### ISSUE TITLE
Module Search should match on module title but doesn't

### ISSUE THREAD

**Issue by bugfolder** [backdrop-ops/backdropcms.org#737]
Role Help (role_help) is a Backdrop module:

https://backdropcms.org/project/role_help

But a search on "Role Help" on the Modules page doesn't return it:

https://backdropcms.org/modules?s=Role+Help

Searching on "Role" or "Help" individually does return it. 

https://backdropcms.org/modules?s=Role
https://backdropcms.org/modules?s=Help

Searching on "role_help" (the machine name of the module) doesn't return anything.

https://backdropcms.org/modules?s=role_help

It seems like if the user enters the exact title or exact machine name, the page ought to return the module in the results.

---

Related: 
* [Fix ordering of add-on search results](https://github.com/backdrop-ops/backdropcms.org/issues/232)
* [Drupal: Search terms: nodes dont appear when using multiple arguments](https://www.drupal.org/node/1615438)

---

Other example search terms

"Block Embed" or
"Views Accordion" or
"JSONPath Parser" or
"Focal Point" or 
"Role help"

**Comment by stpaultim** [comment]
Yes, I just experienced this myself with a number of modules. I could not detect the exact pattern of which modules were being found and which were not. But, here are four modules that I could not find with search at all:

"Block Embed" or 
"Views Accordion" or 
"JSONPath Parser" or 
"Focal Point"

This seems pretty serious, since I think many beginners might not be able to find these modules at all. If you don't know exactly how to hack the URL to find the module, you might easily assume that they are not available for BackdropCMS.org.

**Comment by laryn** [comment]
Seems to be a multi-word search issue perhaps? Is it possible the exposed filter on this view just needs a setting to allow multiple words?

e.g. maybe here:
https://github.com/backdrop-ops/backdropcms.org/blob/main/config/live-active/views.view.modules.json#L656

**Comment by jenlampton** [comment]
I changed [that value](https://github.com/backdrop-ops/backdropcms.org/blob/main/config/live-active/views.view.modules.json#L656) from false to true, but no change in results. 

Also interesting, a search for [Activity Calendar](https://backdropcms.org/modules?s=Activity+Calendar) works just fine. So it might not be a multi-word search issue.

The last time we had this problem we replaced the exposed search filter with a combine fields filter. I'm going to try that again.

**Comment by jenlampton** [comment]
Using the combine fields filter works for all examples provided. I'm going to update theme and layout views, and push the fix. I don't remember why we changed from combined fields back to search, but I remember that when we did I warned against this happening, since we've been here before. Does anyone remember why it was changed? I know there was another issue we were facing, and I'd love to be able to test for that problem, too.

**Comment by jenlampton** [comment]
Okay, I deployed the fix to the live site. I'd love it if others could confirm it's working as expected now: 
https://backdropcms.org/modules?combine=Role+Help

**Comment by jenlampton** [comment]
I was playing around with the search, and I remembered the problem! It was the sort order of the results. 

See a search for webform: https://backdropcms.org/modules?combine=webform

**Comment by jenlampton** [comment]
I don't know if we tried the views patch from https://www.drupal.org/node/1615438, I'm going to revert to search filters and see if that helps.

**Comment by jenlampton** [comment]
That seems to fix it! 
I have created a core issue to track the fix: https://github.com/backdrop/backdrop-issues/issues/4938
And committed and deployed the fix. Would still love confirmation that things are okay now: 
https://backdropcms.org/modules?s=role+help

**Comment by bugfolder** [comment]
Works on "Role Help", "Role", and "Help". Still doesn't return on "role_help", which would be nice, but understandable if not. Thanks for the fix!

**Comment by klonos** [comment]
> Still doesn't return on "role_help"...

Yeah, I don't think that we include the project machine name in the filters/search. Perhaps we should.

**Comment by jenlampton** [comment]
I think we can add it into the search index via the display mode settings. I'll give that a try (changing the view won't help, since we're now using the search index)

**Comment by BWPanda** [comment]
This all seems to be working now. I can search by multiple terms, machine name, etc. Should we close this issue now?

**Comment by jenlampton** [comment]
Yes. Thank you for testing!
