### ISSUE TITLE
Telemetry Data Incorrect

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#866]
I'm going to open an issue here and possibly also in core issue queue, because this might need the attention of core developers and I'm not sure where the error is (telemetry module or on B.Org). 

I'm looking at Telemetry data today and it simply can't be correct. For this to be correct, over 1300 websites would have had to manually enabled the telemetry module already, pretty much on their own without any real encouragement (since we have not really asked people to enable it yet). That does not seem plausible to me. 

If we are going to start collecting this data by default, I think we should make sure that the module is working correctly and our data is useful. 

![image](https://user-images.githubusercontent.com/3144571/148150198-dae3555b-d74d-4593-b687-35dbd2c23657.png)

**Comment by BWPanda** [comment]
Definitely something screwy going on here:

![image](https://user-images.githubusercontent.com/2385329/148157344-a269c2aa-8b57-4a83-b9fb-8a6d5325debe.png)

**Comment by klonos** [comment]
@larsdesigns could this be related to the SQL error you mentioned in the "Infrastructure" thread in Zulip?

**Comment by quicksketch** [comment]
Huh, maybe because we enabled it by default recently? I bet you that our test runs are sending Telemetry data, as was happening with SimpleTest a few years ago. Since every test run spins up 9 sandboxes, that's a lot of new installs happening.

Telemetry data expires pretty quickly, so this number should go back down as test runs reduce. We should of course fix Telemetry reporting so that demo sandboxes and test runs do not count. We'll probably need to fix tests in core, while the sandboxes should be fixed in our Tugboat repository (perhaps overridding settings.php). However I don't think we necessarily need to do anything on BackdropCMS.org.

**Comment by larsdesigns** [comment]
@klonos,  I am not seeing any new errors in the SQL log. I am happy to help with testing. However, I am thinking that @quicksketch is on the right track by looking at the app.

**Comment by BWPanda** [comment]
> while the sandboxes should be fixed in our Tugboat repository (perhaps overridding settings.php).

@quicksketch Can you please elaborate on that? How do we disable modules from settings.php?

**Comment by BWPanda** [comment]
@quicksketch If I were to add a script to the Tugboat install process for removing the Telemetry module, I believe I'd have to bootstrap Backdrop, etc. in order to be able to call `module_disable()`, right?

Would a better solution be to create a separate issue for adding the ability to disable modules from install profiles via settings.php? E.g. We add a call to `settings_get()` in [`install_profile_info()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21install.inc/function/install_profile_info/1) to check for any listed modules and then remove them from the install process?

**Comment by docwilmot** [comment]
Or add to `telemetry_cron()` a conditional for `if settings_get(`telemtery_send_enabled`, TRUE)`. That way the sandboxes will still have the module UI for users to explore. Then of course `$settings['telemtery_send_enabled'] = FALSE;` in `settings.local.php` in the  root `.tugboat` folder. 

Finally, the test runs are in fact enabling Telemetry. My fault; I had the module being enabled in a [Dashboard test setUP() function](https://github.com/backdrop/backdrop/blob/73887c149afedcb6eea982c62d2f5ad817ce0fe8/core/modules/dashboard/tests/dashboard.test#L15) when we were adding a Dashboard block, and forgot to delete that.

**Comment by docwilmot** [comment]
PR done.

**Comment by BWPanda** [comment]
Can we close this now?

**Comment by BWPanda** [comment]
Gonna assume 'yes'.
