### ISSUE TITLE
Fix the newsletter sigup form, and the subscription signup page.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#992]
I don't know what happened to our mailjet signup form, but since we are using civi now I am tempted to let that die and instead set up a fancy new civi form :)

Steps;
1) Theme Civi forms to look like the rest of the site  -- this can be done directly in the borg theme, but maybe in a new component file that is only included if the site is running civi 
2) Update or redirect [the old newsletter page](https://backdropcms.org/newsletter) to [the new subscriptions page](https://backdropcms.org/civicrm/mailing/subscribe). See if we can keep the text from the old subscribe page, and get rid of the civi mess on the new page.
3) Figure out how to embed a civi form onto other websites. -- this may not be possible with civi, but it is possible by building a webform, hooking the webform up to civi, and then embedding the webform into other sites. Check for the civi solution first though :)
4) Style the embedded form to look nice in the borg theme
5) Replace the broken newsletter signup block on all other sites.

**EDIT by @bugfolder**

Sites to be updated with new block (install `borg_signup` module, edit settings.local.php, position block):
- [x] backdropcms.org
- [x] beta.backdropcms.org
- [x] docs.backdropcms.org
- [x] events.backdropcms.org
- [x] forum.backdropcms.org

localize.backdropcms.org doesn't have a newsletter block.

**Comment by bugfolder** [comment]
> I don't know what happened to our mailjet signup form

It's still there, just the block disabled on the home page (see FOOTER section): https://backdropcms.org/admin/structure/layouts/manage/home. But yes, the functionality for signing up from any page (let alone from other sites) is effectively broken since the master list is now a CiviCRM group.

When we introduced CiviCRM, we made the newsletter signup a CiviCRM group that people subscribe to from the Subscriptions sub-tab of their account edit page (and we poured all existing subscriptions into that group via a CiviCRM import). And then yes, there's the CiviCRM-provided Subscription page linked above.

**Comment by jenlampton** [comment]
> just the block disabled on the home page

Yeah, i went around and disabled it on all the other sites too. Even where it was still showing, it is broken on the MailJet side.

> we made the newsletter signup a CiviCRM group that people subscribe to from the Subscriptions sub-tab of their account edit page

We need to get a newsletter signup form onto the site footers again, but one where people can add an email address (but not need an account, or even to log in). Civi should have one of these, I think?

I'm sure we can have civi contacts without user accounts, since most organizations have mailing lists, but very few allow people on the mailing list  to log into their site. I think that was how we imported our previous mailing list...  but it's definitely what we'll need to do for all the Drupal 7 site owner mailing list, since there will be so many of them.

**Comment by bugfolder** [comment]
Civi make it easy to create standalone profile forms (the new subscriptions page is an example), but I don't know of an easy way (or even a hard way) to put a functioning profile page from one site onto a different site.

But I was thinking it would be straightforward to write a custom module that could be installed on all our sites that creates a block containing a Backdrop form that accepts an email address, and upon submission it then calls a URL on b.org, passing the email address and a site-specific authorization token via query parameters in the URL (including a token so that only *.b.org senders could make valid submissions to the b.org recieving URL), and then the b.org version of the module would receive that URL call and perform the necessary CiviCRM manipulations via the Civi APIv4.

That wouldn't require the user to create a user account on any of the sites, although if they had one on b.org, they could then alter their preferences on their user edit page. People with no user account could still unsubscribe at any time via the unsubscribe links in all emails.

How does that sound? I think it's not too hard to implement as a custom module (famous last words), but perhaps there's considerations I'm overlooking, or better ways of doing things.

**Comment by jenlampton** [comment]
> to put a functioning profile page from one site onto a different site.

I don't think we need the whole profile page. We just need a simple email signup form (one that has only an email field, the GDPR checkbox, and a submit button). That form, when posted, would send the values to the civi installation, and the civi installation will create the profile. 

If civi doesn't have this feature already (which is possible, [I found this](https://docs.civicrm.org/formprocessor/en/latest/sign-up-newsletter/) as an alternative approach), then we can probably create the simplified form using a webform. 

I think webform_civicrm will allow us to connect the email field on the webform to the email address part of the contact record.

Webform then has some modules that would allow that form to be embedded on any other site (I think using an iFrame, but maybe now also with JS). -- We may need to ask @quicksketch which module, I found https://www.drupal.org/project/web_widgets but I don't think that's what he used on webform.com.

**Comment by jenlampton** [comment]
> But I was thinking it would be straightforward to write a custom module that could be installed on all our sites that creates a block containing a Backdrop form that accepts an email address, and upon submission it then calls a URL on b.org, passing the email address and a site-specific authorization token via query parameters in the URL (including a token so that only *.b.org senders could make valid submissions to the b.org recieving URL), and then the b.org version of the module would receive that URL call and perform the necessary CiviCRM manipulations via the Civi APIv4.

That would probably also work!  To me, this sounds like a lot more work than making an embeddable webform on one site, and then copy/pasting the embed code onto the others :) The work required for that "embeddable" piece is still unknown in my equation, so it's really hard to compare. 

Here's what the "embed code" looks like from webform.com:

```
<div id="webform-12345">Fill out my <a href="https://norcal.webform.com/form/12345">webform</a>.</div>
<script type="text/javascript">(function(d, s, id) {
var js, wjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = '//webform.com/external/embed.js';
js.onload = js.onreadystatechange = function() {
  var rs = this.readyState; if (rs && rs !== 'complete' && rs !== 'loaded') return;
  try { webformEmbed('https://norcal.webform.com/form/12345?embed=1', 'webform-12345'); } catch (e) {}
};
wjs.parentNode.insertBefore(js, wjs);
}(document, 'script', 'webform-embed'));</script>
```

**Comment by bugfolder** [comment]
Interesting! Looks pretty clean. I wonder if `webform_civicrm` module (which I've not used, just looked at occasionally) would make things easier than the "CMRF Core" module approach described on the "alternative approach" page linked above.

**Comment by jenlampton** [comment]
I am drawn to the webform civi idea since I suspect we'll end up using it
for a bunch of other things (like event registration, donations, etc) in
the future.

**Comment by bugfolder** [comment]
I've tinkered a bit with Webform CiviCRM. When creating a "Tags and Groups" field (necessary to select the "Newsletter" group), the select option to choose just the "Newsletter" group doesn't seem to work. If one selects just "Newsletter", like this:

![image](https://github.com/backdrop-ops/backdropcms.org/assets/29214084/0bfb091d-d5c3-4c39-8b0b-888c57de1aa9)

the field isn't included in the Webform after saving. (Choosing instead "- User Select-" does include the Newsletter field, and all of the others, which we don't want.)

This may be an issue with Webform CiviCRM module. 

At any rate, I've not been able to create a simple Webform that just collects the CiviCRM email address and the "Newsletter" group setting (let alone check whether it handles all combinations of existing/non-existing contact records).

Conversely, creating a form in a block that collects the email address and then uses Civi APIv4 to perform the necessary Civi-tweaking upon submission was pretty straightforward (just 138 LOC in the module file). So I'm inclined to use that as the basis for exploring the cross-site communication.

**Comment by bugfolder** [comment]
Added a PR that creates the form-in-a-block mentioned above. This does the job locally. TBD is the cross-site implementation.

**Comment by bugfolder** [comment]
Hmmm, I just found that CiviCRM APIv4 provides HTTP/REST bindings, which suggests that a form hosted on any Backdrop site could talk to the CiviCRM instance on b.org. This looks worth exploring.

https://docs.civicrm.org/dev/en/latest/api/v4/rest/

**Comment by jenlampton** [comment]
♥️♥️♥️

**Comment by jenlampton** [comment]
@bugfolder I've merged the PR because it is a separate module that we can leave safely disabled as we iterate. We could also create a different module for the other sites if you wanted to leave this as-is for the main site, and do the others in a different way.

Thanks so much for investigating the webform embed option, but I'm also pleased this option was as easy to set up as you expected.

**Comment by jenlampton** [comment]
Iterating: I think we need a (required) opt-in checkbox for GDPR (we added one at some point b/c of GDPR) but the default-value ca be checked. Here's a screenshot of the previous form (from the [wayback machine](https://web.archive.org/web/20210311210113/https://backdropcms.org/))  

<img width="803" alt="Screenshot 2023-05-29 at 3 05 57 PM" src="https://github.com/backdrop-ops/backdropcms.org/assets/397895/01f1f866-0b60-4808-a083-f59c34e5816d">

Here's the current form :) 

<img width="803" alt="Screenshot 2023-05-29 at 3 05 57 PM" src="https://github.com/backdrop-ops/backdropcms.org/assets/397895/d27ed5e2-94ab-44c0-a2d5-cf1a5cbd1302">

**Comment by jenlampton** [comment]
I made those changes, what do we think of this? :) 
<img width="656" alt="Screenshot 2023-05-29 at 3 36 04 PM" src="https://github.com/backdrop-ops/backdropcms.org/assets/397895/adb71da0-a06f-4af6-bd8e-ec37fa0b73f8">

**Comment by bugfolder** [comment]
It looks good. I have the full cross-site version working in my branch, was going to update the PR (I'd labeled it "needs work"), but I see it's been merged.

More commentary to come later today.

**Comment by bugfolder** [comment]
OK, I've now finished the module (at least, it's ready for review). Since the half-finished PR got merged, I've created a new PR, https://github.com/backdrop-ops/backdropcms.org/pull/998, which is built on top of the changes added above. This module implements both local and cross-site signups (in fact, even the "local" signups are done "cross-site").

Some explanation of the approach.

I did look into the REST interface for APIv4, and it looked like the local calls to the PHP API could (in principle) be replaced by cross-site REST API calls. But just the simple act of signing up an email address potentially required several API calls, and having those multiple calls go back and forth across the interwebs seemed like a fragile thing to do; it seems better to have the cross-site call be a single "atomic" action, with all of the CiviCRM API calls encapsulated in a single server-side function.

So i set that up, and then discovered that CiviCRM APIv4 is much stricter about authorization than APIv3 was. That is, many of the APIv4 calls that worked when logged in failed (with Authorization exceptions) for anonymous users. Since the cross-site communication is done as an anonymous visitor, I went back and re-implemented all the CiviCRM stuff using the APIv3 (which is still supported, and will probably be supported for a long time to come, since there's a lot of code out there that's built on it). And this seems to work.

So now, the way things work is, you install this module on _all_ sites, and it creates a signup block on each site. When a person submits the form in the block, it posts a call to an endpoint on b.org (as an anonymous user), which then effects the signup and returns a response code. There is a site key (`BORG_SIGNUP_KEY`) that must be in the `POST` variables so that only authorized sites can use the signup service.

Even the local b.org block will use the same technique; it sends itself the same signup message that any other (authorized) site would do.

I've tested this locally, and it worked, so I think it's ready to try out on the live site. But please take a look at the code first to make sure I've not overlooked something important.

**Comment by bugfolder** [comment]
> But please take a look at the code first to make sure I've not overlooked something important.

That ❤️ looks like a "yes", so I'll proceed with putting it on the site(s) and testing it.

**Comment by bugfolder** [comment]
Reopening because CSS is still to be added.

**Comment by bugfolder** [comment]
Installed the module on forum.backdropcms.org, added the block to the bottom of the home page:

https://forum.backdropcms.org/forum

Signup works! I.e., entering an address here resultings in a (new or existing) CiviCRM contact on b.org receiving the "Newsletter" group.

Next will be to update the CSS in borg theme to use the `.block-borg-signup-borg-signup` selector instead of the old `.block-block-newsletter` selector.

Then

* Install module on other *b.org sites
* go find all occurrences of the old Newsletter block on the various layouts and replace with the new block.

**Comment by jenlampton** [comment]
We need to make a new release of the Borg theme and get it on all the other
sites too. I can handle that part! I had a tab open to do a more thorough
review of the code, but my initial review and ❤️ was definitely in
support!!! This is so exciting!

**Comment by jenlampton** [comment]
> This should be removed (just noting it here so I don't forget).

I've done that :) 

> That still changes the selector to .block-borg-signup-newsletter, so I updated components.css in the borg theme to use the new selector.

Err, oops. I had already updated the borg theme after I merged the first PR. Sorry, I could have saved you some time on that!  I'll make a new release of the theme and update our sites, so that we can get that block safely back in the footer (on all sites) :) 

> There is still some CSS needed, because the block is too wide at the bottom of the page and covers up Drop:

No CSS needed, we just need to add the correct classes to the block in config. Fixed! :) https://forum.backdropcms.org/

**Comment by bugfolder** [comment]
> I'll handle this, as I've been meaning to review footer block strategy on borg sites anyway :)

Great, I'll leave the remaining stuff in your hands for now (to avoid dueling commits). Nice to finally get this working again!

And if I may take this opportunity to rant a bit about CiviCRM: they introduced a new behavior in APIv4, which is that any APIv4 call depends on the permissions given to the logged-in user running the code making the call, so that if the code is being called by an anonymous user (like, say, Backdrop cron, or a remote site like we're doing here), the result of the API call can be different from if the user was a privileged logged-in user (like an admin who happens to be logged in while testing code). Well, yes, permissions matter; but `civicrm_api4()`is a very low-level function. It's as if `db_query()` had different behavior depending on whether the current user was logged in or not. APIv3 behaves the way one would expect (it's up to the calling code to verify permissions). So nearly identical calls in APIv3 and APIv4 can behave very differently, and I'll bet that this has bitten (and/or will continue to bite) people moving from the former to the latter. [\end of rant.]

**Comment by jenlampton** [comment]
Block config underway...  Newsletter page updated!  https://backdropcms.org/newsletter

Sorry the civi4 API is being dumb :( Feel free to post that rant in the civi queue too, if it makes you feel better :)

**Comment by bugfolder** [comment]
From this Zulip thread, some blocks are still missing on Forum:

https://github.com/backdrop-ops/backdropcms.org/issues/992#issuecomment-1571233929

> Steve Moorhouse (DrAlbany): It looks to be the same on all of the sub forums... but the main page is fine.
>
> https://forum.backdropcms.org/forum/other
>
> Steve Moorhouse (DrAlbany): Just checked a few more...
>
> This is fine...
> https://forum.backdropcms.org/forum
> 
>But these aren't
>https://forum.backdropcms.org/forum/how-and-troubleshooting
>https://forum.backdropcms.org/forum/requests-and-feedback
>https://forum.backdropcms.org/forum/help-wanted-job-listings
>...

Etc.

I'll go update the blocks shortly (when fast internet connection returns).

**Comment by bugfolder** [comment]
From this Zulip thread, some blocks are still missing on Forum:

> Steve Moorhouse (DrAlbany): It looks to be the same on all of the sub forums... but the main page is fine.
>
> https://forum.backdropcms.org/forum/other
>
> Steve Moorhouse (DrAlbany): Just checked a few more...
>
> This is fine...
> https://forum.backdropcms.org/forum
> 
>But these aren't
>https://forum.backdropcms.org/forum/how-and-troubleshooting
>https://forum.backdropcms.org/forum/requests-and-feedback
>https://forum.backdropcms.org/forum/help-wanted-job-listings
>...

Etc.

I'll go update the blocks shortly (when fast internet connection returns).

**Comment by bugfolder** [comment]
I've now updated all the Forum layouts with the new Newsletter signup blocks. (I left the old blocks disabled just in case, but at this point they could probably be safely deleted.)

**Comment by bugfolder** [comment]
> I've added a checklist of sites to update to the description so we can better track the progress.

I was not able to find that, so I've added a list [to the first comment in this issue](https://github.com/backdrop-ops/backdropcms.org/issues/992#issue-1675806958), and will work on the other sites.

**Comment by bugfolder** [comment]
I've added the `borg_signup` module to docs.b.org, added the code bits to settings.local.php, added the block to the Default layout with the same CSS class as on b.org. But on the home page https://docs.backdropcms.org, the newsletter block is ill-positioned. Comparing sites, I see that on b.org, the footer is wrapped in a `<div class="row">` and on docs, it isn't (and that wrapper div would indeed be needed for the Bootstrap class on the block to do its thing). So presumably the API BORG theme (on docs) needs some tweaking. Calling on @jenlampton to weigh in on this.

**Comment by bugfolder** [comment]
Never mind, found where the `<div class="row">` needed to be added (to the Moscone layout template in `api_borg` theme). Block is now in the right place on docs.

**Comment by bugfolder** [comment]
So I think this task is now done. Closing the issue. (Reopen if I missed something.)
